language: python

matrix:
  include:
    - python: 3.6

install:
  - pip install .
    # need this because some requirements are pulled from git
    # which is ignored in the setup.py file
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - coverage run run_tests.py
  - coverage report -m

after_success:
  - codecov
